openapi: 3.2.0
info:
  title: Redmine REST Custom Fields.json API
  description: REST API for Redmine project management. Base URL is your Redmine instance URL.
  version: 1.0.0
servers:
- url: https://{redmine_host}
  description: Redmine instance
  variables:
    redmine_host:
      default: redmine.example.com
security:
- apiKeyHeader: []
- apiKeyQuery: []
- basicAuth: []
tags:
- name: Custom Fields.json
paths:
  /custom_fields.json:
    get:
      summary: List custom fields
      responses:
        '200':
          description: Custom fields
      tags:
      - Custom Fields.json
      operationId: getCustomFieldsJson
      x-operation-id-source: derived
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      in: header
      name: X-Redmine-API-Key
    apiKeyQuery:
      type: apiKey
      in: query
      name: key
    basicAuth:
      type: http
      scheme: basic
